// <auto-generated />
using System;
using EFCore.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201011223632_Initial_EFCore_3_1_8")]
    partial class Initial_EFCore_3_1_8
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCore.Domain.Developers.Developer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DevType")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Developer");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Developer");
                });

            modelBuilder.Entity("EFCore.Domain.Motivations.Motivation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeveloperId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Factor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId")
                        .IsUnique()
                        .HasFilter("[DeveloperId] IS NOT NULL");

                    b.ToTable("Motivation");
                });

            modelBuilder.Entity("EFCore.Domain.Tasks.Skill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("EFCore.Domain.Tasks.SkillTaskToDo", b =>
                {
                    b.Property<long>("SkillsId")
                        .HasColumnType("bigint");

                    b.Property<long>("TasksToDoId")
                        .HasColumnType("bigint");

                    b.HasKey("SkillsId", "TasksToDoId");

                    b.HasIndex("TasksToDoId");

                    b.ToTable("SkillTaskToDo");
                });

            modelBuilder.Entity("EFCore.Domain.Tasks.TaskToDo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeveloperId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.ToTable("TaskToDo");
                });

            modelBuilder.Entity("EFCore.Domain.Developers.BackEndDeveloper", b =>
                {
                    b.HasBaseType("EFCore.Domain.Developers.Developer");

                    b.Property<string>("DatabasePreference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DatabaseStack")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("BackEndDeveloper");
                });

            modelBuilder.Entity("EFCore.Domain.Developers.FrontEndDeveloper", b =>
                {
                    b.HasBaseType("EFCore.Domain.Developers.Developer");

                    b.Property<string>("FrameworkPreference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MobileStack")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("FrontEndDeveloper");
                });

            modelBuilder.Entity("EFCore.Domain.Developers.FullStackDeveloper", b =>
                {
                    b.HasBaseType("EFCore.Domain.Developers.Developer");

                    b.Property<string>("CloudPreference")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("FullStackDeveloper");
                });

            modelBuilder.Entity("EFCore.Domain.Motivations.Motivation", b =>
                {
                    b.HasOne("EFCore.Domain.Developers.Developer", null)
                        .WithOne("Motivation")
                        .HasForeignKey("EFCore.Domain.Motivations.Motivation", "DeveloperId");
                });

            modelBuilder.Entity("EFCore.Domain.Tasks.SkillTaskToDo", b =>
                {
                    b.HasOne("EFCore.Domain.Tasks.Skill", "Skill")
                        .WithMany("TasksToDo")
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCore.Domain.Tasks.TaskToDo", "TaskToDo")
                        .WithMany("Skills")
                        .HasForeignKey("TasksToDoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCore.Domain.Tasks.TaskToDo", b =>
                {
                    b.HasOne("EFCore.Domain.Developers.Developer", null)
                        .WithMany("TasksToDo")
                        .HasForeignKey("DeveloperId");
                });

            modelBuilder.Entity("EFCore.Domain.Developers.FullStackDeveloper", b =>
                {
                    b.OwnsOne("EFCore.Domain.Motivations.ExtraMotivation", "ExtraMotivation", b1 =>
                        {
                            b1.Property<string>("FullStackDeveloperId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Factor")
                                .HasColumnType("varchar(50)");

                            b1.HasKey("FullStackDeveloperId");

                            b1.ToTable("Developer");

                            b1.WithOwner()
                                .HasForeignKey("FullStackDeveloperId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
